config/routes.rb
Rails.application.routes.draw do

  resources :datstatuses

  #rotas para o devise
    #rotas para registar utlizadores devido a ter removido o :registerable do model de users
  # devise_scope :user do
  #   get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
  #   get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  # end
    #rotas para todo o resto do devise
  devise_for :users
  resources :users
  
  
  get 'welcome/start'
  get 'welcome/whatisit'
  get 'welcome/history'
  get 'welcome/goals'
  get 'welcome/structure'
  get 'welcome/faq'

  resources :groles

  resources :roles
 
  resources :routes

  namespace :systems do
    resources :types
  end
  resources :systems
  resources :releases
  resources :companies

  resources :datfiles
  resources :collection_types
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :datfiles
  has_many :grole
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include Accessible
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include Accessible
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :prepare_form_data
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy

    if current_user.id != @user.id

      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end

    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    def prepare_form_data
      if(user_signed_in?)
        @links = Grole.where(user_id: current_user.id).joins("inner join routes r on groles.route_id = r.id").order("r.priority asc, name")
        if current_user.admin?
            @linksR = Grole.where(user_id: 0, role_id:1).joins("inner join routes r on groles.route_id = r.id").order("r.priority asc, name")
        end
        if current_user.mod?
            @linksR = Grole.where(user_id: 0, role_id:2).joins("inner join routes r on groles.route_id = r.id").order("r.priority asc, name")
        end
        if current_user.pub?
            @linksR = Grole.where(user_id: 0, role_id:3).joins("inner join routes r on groles.route_id = r.id").order("r.priority asc, name")
        end
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      #  params.require(:user).permit(:admin, :username, :email, :password)
       params.require(:user).permit(:admin, :mod, :pub, :username, :email, :password)
    end
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>&nbsp;</p>
  <div class="field">
    <%= f.label :admin %>
    <%= f.check_box :admin %>
    &nbsp;&nbsp;&nbsp;&nbsp;
    <%= f.label :mod %>
    <%= f.check_box :mod %>
    &nbsp;&nbsp;&nbsp;&nbsp;
    <%= f.label :pub %>
    <%= f.check_box :pub %>
  </div>
  <p>&nbsp;</p>
  <div>
    <%= f.label :username, class: 'form-label' %>
    <%= f.text_field :username, class: 'form-control' %>
  </div>
  <p>&nbsp;</p>
  <div>
    <%= f.label :email, class: 'form-label' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <p>&nbsp;</p>
  <div>
    <%= f.label :password, class: 'form-label' %>
    <%= f.text_field :password, class: 'form-control' %>
  </div>
  <p>&nbsp;</p>

  <!-- <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
  </div> -->

  <!-- <div class="actions">
    <%= f.submit %>
  </div> -->

  <p class="text-right">
    <%= link_to 'Cancel', users_path, class: 'btn btn-default' %>    
    <%= f.submit 'Save', :class => 'btn btn-success' %>
 </p>

  <%#= params.inspect %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1>Users</h1>

<div class="table-responsive text-nowrap">
  <% if can? :create, User %>
    <div class="text-left">
        <%= link_to 'New User', new_user_path, class: 'btn btn-primary' %>
    </div>
  <% end %>
<p>&nbsp;</p>
  <table class="table table-hover">
    <tr>
      <th>Administrator</th>
      <th>Moderator</th>
      <th>Publisher</th>
      <th>User Name</th>
      <th>Email</th>
      <th></th>
    </tr>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.admin %></td>
        <td><%= user.mod %></td>
        <td><%= user.pub %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td class="text-right">
            <%= link_to '<i class="glyphicon glyphicon-eye-open"></i>'.html_safe, user , class: 'btn btn-default'%>
            <% if can? :update, User %>
            <%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_user_path(user) , class: 'btn btn-default'%>
            <% end %>
            <% if can? :destroy, User %>
              <% if current_user.id != user.id %>
              <%= link_to '<i class="glyphicon glyphicon-remove"></i>'.html_safe, user, 
              method: :delete, 
              data: { confirm: 'Are you sure you want to delete this user?' }, class: 'btn btn-default' %>
              <% end %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<h1>New User</h1>
<div class="bg-danger" style="border:1px solid #000; padding:5px;">
    <p>Esta funcionalidade só é possivel sem o atributo registrable do Model->users.rb</p>
    <p>Não dará para registar um utilizador novo porque já existe um autenticado.</p>
</div>


<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h2>
  User</h2>
  <hr>

<% if current_user.admin? %>
  <p>
    <strong>Administrator:</strong>
    <%= @user.admin %>
  </p>
<% end %>

<% if current_user.mod?  or current_user.admin?%>
  <p>
    <strong>Moderator:</strong>
    <%= @user.mod %>
  </p>
<% end %>

<% if current_user.pub? or current_user.admin?%>
  <p>
    <strong>Publisher:</strong>
    <%= @user.pub %>
  </p>
<% end %>

<p>
  <strong>User Name:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<hr>

<div class="text-right">
  <%= link_to 'Back', users_path, class: 'btn btn-default' %>
    <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary' %>
    <% if current_user.id != @user.id %>
      <%= link_to 'Destroy', user_path(@user), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
</div>


<!-- <%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> -->