config/routes.rb
Rails.application.routes.draw do

  resources :datstatuses

  #rotas para o devise
    #rotas para registar utlizadores devido a ter removido o :registerable do model de users
  # devise_scope :user do
  #   get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
  #   get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  # end
    #rotas para todo o resto do devise
  devise_for :users
  resources :users
  
  
  get 'welcome/start'
  get 'welcome/whatisit'
  get 'welcome/history'
  get 'welcome/goals'
  get 'welcome/structure'
  get 'welcome/faq'

  resources :groles

  resources :roles
 
  resources :routes

  namespace :systems do
    resources :types
  end
  resources :systems
  resources :releases
  resources :companies

  resources :datfiles
  resources :collection_types
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end

      if user.mod?
        can :update, :all
      else
        can :read, :all
      end

      if user.pub?
        can :read, :all
      else
        can :read, :all
      end

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection_type.rb
class CollectionType < ApplicationRecord
    has_many :datfile
    validates :name, presence: true,length: { minimum: 5 }
    validates :desc, presence: true,length: { minimum: 5 }    
end

app/models/company.rb
class Company < ApplicationRecord
    has_attached_file :image, styles: { medium:"300x300", thumb: "150x150#"}
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    has_many :systems
    validates :title, presence:true, length: {minimum: 2}
    validates :text, presence:true, length: {minimum: 6}
end

app/models/datfile.rb
class Datfile < ApplicationRecord
  has_attached_file :file
  
  # do_not_validate_attachment_file_type :file
  
  validates_attachment_content_type :file, :content_type => ['text/html','text/xml','application/xml'], file_name: { matches: /\.dat\z/ }
  # validates_attachment :file, :presence => true, file_name: { matches: /\.dat\z/ }
  # validates_attachment_content_type :file, content_type: /\.dat\z/

  belongs_to :collection_type, required: true
  belongs_to :user, required: true
  belongs_to :system, required: true
  belongs_to :datstatus, required: true
  has_and_belongs_to_many :releases
  
  validates :name, presence: true,length: { minimum: 5 }
  validates :readme, presence: true,length: { minimum: 5 }  
  validates :collection_type_id, presence: true
  validates :system_id, presence: true  
  validates :datstatus_id, presence: true  
  validates :user_id, presence: true  
  #validates_attachment_file_name :file, :matches => [/c\Z/i]
  do_not_validate_attachment_file_type :file
end

app/models/datstatus.rb
class Datstatus < ApplicationRecord
    has_many :datfile
    validates :name, presence: true,length: { minimum: 2 }
end

app/models/grole.rb
class Grole < ApplicationRecord
  belongs_to :user
  belongs_to :role
  belongs_to :route
end

app/models/release.rb
class Release < ApplicationRecord
    validates :descRelease, presence: true,
    length: { in: 5..255 }
    has_and_belongs_to_many :datfiles
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :grole
    validates :name, presence: true,
                    length: { minimum: 1 }
end

app/models/route.rb
class Route < ApplicationRecord
    has_many :grole
    validates :name, presence: true,
                    length: { minimum: 1 }
    validates :path, presence: true,
                    length: { minimum: 1 }
    validates :priority, presence: true,
                    length: { minimum: 1 }
end

app/models/system.rb
class System < ApplicationRecord
    has_attached_file :image, styles: { medium:"300x300", thumb: "150x150#"}
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    belongs_to :company
    belongs_to :systemsType
    has_many :datfiles
    validates :name, presence: true, length: { in: 3..255 }
    validates :abbreviation, presence: true, length: {  in: 1..10 }
    validates :company_id, presence: true
    validates :systemsType, presence: true
    validates :dateRelease, format: { with: /\d{4}\-(0?[1-9]|1[012])\-([12][0-9]|3[01]|0?[1-9])/,
    message: "only date" }
end

app/models/systems_type.rb
class SystemsType < ApplicationRecord
    has_many :system
    validates :name, presence: true, length: { in: 3..255 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :datfiles
  has_many :grole
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    before_action :authenticate_user!
    before_action :prepare_form_data
    def index
        @companies = Company.order("title").page(params[:page]).per(20)
    end 
    
    def show
        @company = Company.find(params[:id])
    end

    def new
        @company = Company.new
    end

    def edit
        @company = Company.find(params[:id])
    end

    def create
        @company = Company.new(company_params)

        if @company.save
            redirect_to @company
          else
            render 'new'
        end
    end

    def update
        @company = Company.find(params[:id])
        
         if @company.update(company_params)
           redirect_to @company
         else
           render 'edit'
         end
    end
       
    def destroy
        @company = Company.find(params[:id])
        @company.destroy
       
        redirect_to companies_path
    end

    private
    def company_params
        params.require(:company).permit(:title, :text, :image)
    end
    def prepare_form_data
        if(user_signed_in?)
            @links = Grole.where(user_id: current_user.id).joins("inner join routes r on groles.route_id = r.id").order("r.priority asc, name")
            if current_user.admin?
                @linksR = Grole.where(user_id: 0, role_id:1).joins("inner join routes r on groles.route_id = r.id").order("r.priority asc, name")
            end
            if current_user.mod?
                @linksR = Grole.where(user_id: 0, role_id:2).joins("inner join routes r on groles.route_id = r.id").order("r.priority asc, name")
            end
            if current_user.pub?
                @linksR = Grole.where(user_id: 0, role_id:3).joins("inner join routes r on groles.route_id = r.id").order("r.priority asc, name")
            end
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  #verifica a existencia de um asset logical_path em localizações diferentes conforme se o server esta em producao ou em dev
    def asset_available? logical_path
        if Rails.configuration.assets.compile
          Rails.application.precompiled_assets.include? logical_path
        else
          Rails.application.assets_manifest.assets[logical_path].present?
        end
      end  
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/datfiles_helper.rb
module DatfilesHelper
end

app/helpers/groles_helper.rb
module GrolesHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/_form.html.erb
<%= form_with model: @company, local: true do |form| %>

 <% if @company.errors.any? %>
   <div id="error_explanation">
     <h2>
       <%= pluralize(@company.errors.count, "error") %> prohibited
       this company from being saved:
     </h2>
     <ul>
       <% @company.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>

 <div class="form-group">
 <p>
   <%= form.label :title, class: 'form-label' %><br>
   <%= form.text_field :title, class: 'form-control' %>
 </p>

 <p>
   <%= form.label :text, class: 'form-label' %><br>
   <%= form.text_area :text, class: 'form-control' %>
 </p>

 <p>
  <%= form.label :image, class: 'form-label' %><br>
  <%= form.file_field :image, class: 'form-control' %>
</p>

 <p class="text-right">
    <%= link_to 'Cancel', companies_path, class: 'btn btn-default' %>    
    <%= form.submit 'Save', :class => 'btn btn-success' %>
 </p>

<% end %>
</div>

app/views/companies/edit.html.erb
<h2>Edit Company</h2>
<%= render 'form' %>
<!-- <%= render '/welcome/bottom' %> -->

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<div>

  <div class="text-right">
    <%= link_to 'New company', new_company_path, class: 'btn btn-primary' %>
      <p>&nbsp;</p>
  </div>
  <div class="text-left">
    <%= paginate @companies %>
  </div>
</div>

<div class="table-responsive text-nowrap">
  <table class="table table-hover">
    <tr>
      <th>Date</th>
      <th>Name</th>
      <th>&nbsp;</th>
    </tr>

    <% @companies.each do |company| %>
      <tr data-toggle="tooltip" title="Click for details">
          <td data-link="<%= company_path(company) %>" >
              <%=  company.created_at.strftime("%F") %>
          </td>
  
          <td width="100%" data-link="<%= company_path(company) %>" >
              <%= company.title %>
        </td>
        <td class="text-right">
          <%= link_to '<i class="glyphicon glyphicon-eye-open"></i>'.html_safe, company_path(company), class: 'btn btn-default' %>
            <%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_company_path(company), class: 'btn btn-default' %>
              <%= link_to '<i class="glyphicon glyphicon-remove"></i>'.html_safe, company_path(company),
        method: :delete,
        data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
        </td>
      </tr>
      <% end %>
  </table>
  <div>
      <div class="text-left">
          <%= paginate @companies %>
        </div>
    <div class="text-right">
      <%= link_to 'New company', new_company_path, class: 'btn btn-primary' %>
    </div>

  </div>
</div>
<!-- <%= render '/welcome/bottom' %> -->

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<!-- <%= render '/welcome/bottom' %> -->

app/views/companies/show.html.erb
<h2>
    Company</h2>
    <hr>
    <%= image_tag @company.image.url(:medium) %>
    <p>
        <div class="table-responsive text-nowrap">
    <strong>Title:</strong>
    <%= @company.title %>
  </p>
   
  <p>
    <strong>Text:</strong>
    <%= @company.text %>
  </p>
  <hr>
  <div class="text-right">
      <%= link_to 'Back', companies_path, class: 'btn btn-default' %>
        <%= link_to 'Edit', edit_company_path(@company), class: 'btn btn-primary' %>
          <%= link_to 'Destroy', company_path(@company), class: 'btn btn-danger',
    method: :delete,
    data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
  <!-- <%= render '/welcome/bottom' %> -->